### ISSUE TITLE
EF error when call ICronTickerManager.UpdateAsync()

### ISSUE THREAD

**Issue by CreateLab** [Arcenox-co/TickerQ#188]
**Description**
When calling `ICronTickerManager.UpdateAsync`, which calls `TickerManager.UpdateCronTickerAsync`, EF Core throws a `DbUpdateException` due to a duplicate entry in the `CronTickers` table.

```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.

MySqlConnector.MySqlException (0x80004005): Duplicate entry '72718173-2daf-48bf-8357-a6e9e3da2469' for key 'CronTickers.PRIMARY'
```

**Cause**
The relationship between `CronTickerOccurrence` and `CronTicker` is not properly configured.
Without an explicit foreign key mapping, EF Core treats the navigation property `CronTicker` as a new entity and tries to insert it again, which leads to a primary key violation.

If we intercept `SaveChangesAsync` and inspect `ChangeTracker.Entries()`:

```csharp
public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = new CancellationToken())
{
    return base.SaveChangesAsync(cancellationToken);
}
```

In the original (broken) version we see **two entities being tracked**:

```
{Count = 2}
    [0]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: b7dbc391-fc92-4cfb-a84c-1685aae74bb2} Added FK {CronTickerId: 6d9e948e-7788-4367-a895-9c19de531b0e}}
    [1]: {CronTickerEntity {Id: 6d9e948e-7788-4367-a895-9c19de531b0e} Added}
```

In the fixed version there is **only one tracked entity** (`CronTickerOccurrence`), which is correct.

**Steps to reproduce**

1. Call `TickerManager.UpdateCronTickerAsync` for an existing `cronTicker`.
2. EF Core attempts to save changes.
3. A duplicate primary key error is thrown.

**Quick fix**
In `TickerManager.UpdateCronTickerAsync`, replace:

```csharp
var generateNextOccurrence = new CronTickerOccurrence<TCronTicker>
{
    CronTicker = cronTicker,
    Status = TickerStatus.Idle,
    ExecutionTime = crontabSchedule.GetNextOccurrence(Clock.UtcNow),
    LockedAt = Clock.UtcNow,
    LockHolder = LockHolder
};
```

with

```csharp
var generateNextOccurrence = new CronTickerOccurrence<CronTicker>
{
    CronTickerId = cronTicker.Id,
    Status = TickerStatus.Idle,
    ExecutionTime = crontabSchedule.GetNextOccurrence(DateTime.UtcNow),
    LockedAt = DateTime.UtcNow,
    LockHolder = LockHolder
};
```

**Better solution**
Configure the entity relationship with a `[ForeignKey]` attribute or Fluent API so EF Core recognizes that `CronTickerOccurrence` should reference an existing `CronTicker` instead of trying to insert it.

**Comment by albert-kunushevci** [comment]
check out v2.5.0 I fixed the issue along with lot's of issues.

**Comment by CreateLab** [comment]
Issue still not fixed

#### Step 1

I updated packages from `2.4.4` → `2.5`:

```xml
<PackageVersion Include="TickerQ" Version="2.5.0" />
<PackageVersion Include="TickerQ.Dashboard" Version="2.5.0" />
<PackageVersion Include="TickerQ.EntityFrameworkCore" Version="2.5.0" />
```

#### Step 2

I changed call from:

```csharp
UpdateCronTickerAsync // custom method with upper fix
```

to:

```csharp
_cronMgr.UpdateAsync
```

where:

```csharp
ICronTickerManager<CronTicker> _cronMgr
```

is resolved from DI.

#### Step 3

I catch everything from:

```csharp
public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = new CancellationToken())
{
    return base.SaveChangesAsync(cancellationToken);
}
```

#### Step 4

Logged ChangeTracker entries:

<details>
<summary>Sample logs</summary>

```
  base.ChangeTracker.Entries().ToList()
  {Count = 1}
    [0]: {CronTickerEntity {Id: b87b520f-ed86-47c5-8c26-bde223365cf9} Modified}

  base.ChangeTracker.Entries().ToList()
  {Count = 1}
    [0]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: e5d54f61-58a2-484c-a59d-010ec400ee47} Added FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}

  base.ChangeTracker.Entries().ToList()
  {Count = 1}
    [0]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 9a96536d-67f1-41ea-b288-3c841689ad1e} Deleted FK {CronTickerId: b87b520f-ed86-47c5-8c26-bde223365cf9}}

  base.ChangeTracker.Entries().ToList()
  {Count = 98}
    [0]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 008d3e39-ecb6-44a0-a2dd-4a52a8eeefa8} Modified FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}
    [1]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 02668fc2-1329-420f-9c68-1272cd979a41} Modified FK {CronTickerId: 77831b68-0ec4-476e-be78-57d03745149d}}
    [2]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 02dbaee7-548c-41a6-acc3-0dcf05753795} Modified FK {CronTickerId: 9ec1c244-07c9-468b-b6c5-84bc931f40de}}
    [3]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 04d0decb-1c0b-4313-bc89-fc2f213e76ca} Modified FK {CronTickerId: c424084b-b8dd-415e-857a-53d1514108d8}}
    [4]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 0bc7b648-ed08-40ed-91f6-cfba5961263c} Modified FK {CronTickerId: d67492b1-89d5-4493-a45e-0873415b7f18}}
    [5]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 0cd7bf43-4349-4bfc-92b8-35defc66e18d} Modified FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}
    [6]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 113af658-3d6b-441b-8ec6-9ef4ec328374} Modified FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}
    [7]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 13111311-bccf-4a75-99e5-24dee131e472} Modified FK {CronTickerId: abc005a9-d164-4834-bf22-c99572148f11}}
    [8]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 17efd044-3527-4946-9a80-5f76a640ebf8} Modified FK {CronTickerId: abc005a9-d164-4834-bf22-c99572148f11}}
    [9]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 20c01f5a-94d0-48a1-9669-6ffa0acb41e7} Modified FK {CronTickerId: 9adac3c6-144b-4e1f-9ae5-ae381473b851}}
    [10]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 2430c3fb-f84b-4eda-b47a-5bed3008168f} Modified FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}
    [11]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 255d1058-9a52-4037-b9b2-0961be570713} Modified FK {CronTickerId: c1f38cce-127d-417c-b826-8397f0e93a40}}
    [12]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 27ebc928-5b43-4d50-bb34-67f47a678dc6} Modified FK {CronTickerId: c1f38cce-127d-417c-b826-8397f0e93a40}}
    [13]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 288e66dd-4fee-4381-8797-777a85a62940} Modified FK {CronTickerId: c424084b-b8dd-415e-857a-53d1514108d8}}
    [14]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 2898401b-4869-4160-b140-63df0df877df} Modified FK {CronTickerId: 77831b68-0ec4-476e-be78-57d03745149d}}
    [15]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 2957c71a-7db4-4607-bd0d-bc85d362760a} Modified FK {CronTickerId: 9adac3c6-144b-4e1f-9ae5-ae381473b851}}
    [16]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 31f5a2e4-0765-47b7-a17e-cd38be2a51fd} Modified FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}
    [17]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 39c7730f-c0e8-49df-bf7d-2691497b3f12} Modified FK {CronTickerId: d67492b1-89d5-4493-a45e-0873415b7f18}}
    [18]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 3a2d635f-7cda-4751-a086-5cc7fc934fda} Modified FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}
    [19]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 3d3d285a-8b17-4a69-a44f-7c413b10ac9f} Modified FK {CronTickerId: d67492b1-89d5-4493-a45e-0873415b7f18}}
    [20]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 3e329b94-af76-463d-a417-b4236d985ce8} Modified FK {CronTickerId: d67492b1-89d5-4493-a45e-0873415b7f18}}
    [21]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 3f3bfbdb-cd12-4a8e-bd63-c70050e215d3} Modified FK {CronTickerId: 9adac3c6-144b-4e1f-9ae5-ae381473b851}}
    [22]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 47aad4c8-24bb-4ec4-b7dc-c3b374e8aa16} Modified FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}
    [23]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 4896e837-dfb1-4f02-864d-5a8e3dc11c80} Modified FK {CronTickerId: 9adac3c6-144b-4e1f-9ae5-ae381473b851}}
    [24]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 48a84c83-268e-45e6-b456-8ff84f041773} Modified FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}
    [25]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 4c7f31aa-dc71-449a-8b6d-55d7ac1f99eb} Modified FK {CronTickerId: c424084b-b8dd-415e-857a-53d1514108d8}}
    [26]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 4d1910c0-a92f-441e-81c5-3fde50ebb256} Modified FK {CronTickerId: abc005a9-d164-4834-bf22-c99572148f11}}
    [27]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 4f2ff91a-85b9-48c6-891c-7e62aa6ee71c} Modified FK {CronTickerId: c1f38cce-127d-417c-b826-8397f0e93a40}}
    [28]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 5036c814-bf7b-4d57-a170-47787a26ad09} Modified FK {CronTickerId: 77831b68-0ec4-476e-be78-57d03745149d}}
    [29]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 5140abd0-fd92-4489-a188-1737f8250fa2} Modified FK {CronTickerId: c424084b-b8dd-415e-857a-53d1514108d8}}
    [30]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 572b36ba-45f3-43fe-b291-5aa6a76725ae} Modified FK {CronTickerId: d67492b1-89d5-4493-a45e-0873415b7f18}}
    [31]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 57fab7c8-6931-4f89-a9b7-da6e603c400b} Modified FK {CronTickerId: abc005a9-d164-4834-bf22-c99572148f11}}
    [32]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 5858cac6-4ba8-4ba0-9bb1-32ca42d2b602} Modified FK {CronTickerId: c1f38cce-127d-417c-b826-8397f0e93a40}}
    [33]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 5ea72946-fd1a-4b1f-8f03-e270ad76cbdc} Modified FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}
    [34]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 716ddeec-d59d-4078-8a41-b5603b274a05} Modified FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}
    [35]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 741c5223-51cb-42ea-995f-e487832f71bb} Modified FK {CronTickerId: 77831b68-0ec4-476e-be78-57d03745149d}}
    [36]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 75e8f43c-4660-401b-98f3-d89fd8e57abf} Modified FK {CronTickerId: c424084b-b8dd-415e-857a-53d1514108d8}}
    [37]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 75f31eb2-508b-4bf7-beaa-522c10836328} Modified FK {CronTickerId: 9adac3c6-144b-4e1f-9ae5-ae381473b851}}
    [38]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 76367e1e-a265-4d79-a8d1-531f8e68c1f5} Modified FK {CronTickerId: abc005a9-d164-4834-bf22-c99572148f11}}
    [39]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 77b49c70-aab7-4c15-ae0a-4d5175c79e91} Modified FK {CronTickerId: 9adac3c6-144b-4e1f-9ae5-ae381473b851}}
    [40]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 7963e6e0-8dc3-4b35-bce8-bd59bcc5d7e8} Modified FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}
    [41]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 7a70d0e4-852b-4d95-a6a4-2a9a7ad466e9} Modified FK {CronTickerId: 77831b68-0ec4-476e-be78-57d03745149d}}
    [42]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 7bf95e78-93d3-4087-bd1f-09e0b38496d9} Modified FK {CronTickerId: d67492b1-89d5-4493-a45e-0873415b7f18}}
    [43]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 7f457376-bb55-4b1b-bf85-bde1e2bf7b70} Modified FK {CronTickerId: abc005a9-d164-4834-bf22-c99572148f11}}
    [44]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 8361f13b-c79a-47d5-8bbd-34f2a625c1ca} Modified FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}
    [45]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 86323bc3-6be2-43fa-8efd-f88a1ca03a26} Modified FK {CronTickerId: b8ced09b-ad1b-47ec-9e65-4e228d2804bd}}
    [46]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 8c3ec1f1-fd17-4de7-aaf9-623b2e70f4ed} Modified FK {CronTickerId: 9adac3c6-144b-4e1f-9ae5-ae381473b851}}
    [47]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 9656faa0-2832-4bae-b91a-eb145aaea80b} Modified FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}
    [48]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 98041983-156d-4b34-b728-2d63be1a1c6a} Modified FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}
    [49]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 9a96536d-67f1-41ea-b288-3c841689ad1e} Modified FK {CronTickerId: b87b520f-ed86-47c5-8c26-bde223365cf9}}
    [50]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 9aaa3d12-10c2-4f93-af24-97a12f4dcb27} Modified FK {CronTickerId: abc005a9-d164-4834-bf22-c99572148f11}}
    [51]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 9cd926c9-3031-46e3-a443-684bd6439000} Modified FK {CronTickerId: c424084b-b8dd-415e-857a-53d1514108d8}}
    [52]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 9dc9233f-3dae-49b6-830e-e517c327dd53} Modified FK {CronTickerId: d67492b1-89d5-4493-a45e-0873415b7f18}}
    [53]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: a2a6bc18-dbde-465b-be7b-a5c291aa9d9f} Modified FK {CronTickerId: c1f38cce-127d-417c-b826-8397f0e93a40}}
    [54]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: a4d84f89-d255-4e52-bd73-228f2a1bc192} Modified FK {CronTickerId: 77831b68-0ec4-476e-be78-57d03745149d}}
    [55]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: a64db30f-434b-4215-b021-a84d63e79050} Modified FK {CronTickerId: d67492b1-89d5-4493-a45e-0873415b7f18}}
    [56]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: abf604df-9171-4765-b9e5-d32b051c7c60} Modified FK {CronTickerId: c1f38cce-127d-417c-b826-8397f0e93a40}}
    [57]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: afecc7e8-bf26-4171-9af2-3b3df81c875f} Modified FK {CronTickerId: c1f38cce-127d-417c-b826-8397f0e93a40}}
    [58]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: b308aff2-6fda-4aa2-87d3-9d2316da4c4f} Modified FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}
    [59]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: b72d4836-8ee5-4b08-ba1e-768adf21f6db} Modified FK {CronTickerId: 9adac3c6-144b-4e1f-9ae5-ae381473b851}}
    [60]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: b943ee6d-d65e-438c-90ea-b4f5b333eb4a} Modified FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}
    [61]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: bcef6eb0-0908-4913-a902-39b5b313646b} Modified FK {CronTickerId: c424084b-b8dd-415e-857a-53d1514108d8}}
    [62]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: c04d93c6-fc40-44d7-98e8-02e9d2d3328e} Modified FK {CronTickerId: c424084b-b8dd-415e-857a-53d1514108d8}}
    [63]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: c16a0699-b87b-4a37-9bc7-7dbc8d509fab} Modified FK {CronTickerId: 9adac3c6-144b-4e1f-9ae5-ae381473b851}}
    [64]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: c9806379-b353-42c6-847c-e3f511a5df6e} Modified FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}
    [65]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: cac4dc0e-2719-4d2b-904b-41316c338b49} Modified FK {CronTickerId: 9adac3c6-144b-4e1f-9ae5-ae381473b851}}
    [66]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: ce1fd4f5-3165-46e9-a4c4-19693b99e62e} Modified FK {CronTickerId: 9eb787da-09e4-4cb7-a780-15340d21fdf2}}
    [67]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: d0367ec2-d321-47a9-8605-af88be734e29} Modified FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}
    [68]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: d1d2f8ec-e124-4188-be66-d35c0db63d13} Modified FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}
    [69]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: d3c20d2a-435a-4c5d-8ee4-ac68f87c970c} Modified FK {CronTickerId: c1f38cce-127d-417c-b826-8397f0e93a40}}
    [70]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: d8589cdf-7810-4284-a8c3-bb227feb26c6} Modified FK {CronTickerId: abc005a9-d164-4834-bf22-c99572148f11}}
    [71]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: d9211315-a05e-4a85-81c1-64d667e04ea1} Modified FK {CronTickerId: d67492b1-89d5-4493-a45e-0873415b7f18}}
    [72]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: da15919a-4a73-4f5f-9365-4ea5fb7a1b69} Modified FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}
    [73]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: df00372e-b99c-4850-b6a7-a1aa8875f44e} Modified FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}
    [74]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: e4418a15-0888-489d-847b-b171750231e3} Modified FK {CronTickerId: c1f38cce-127d-417c-b826-8397f0e93a40}}
    [75]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: e474c1b1-b49a-4c2f-bb83-8a25598854bb} Modified FK {CronTickerId: d85df830-4d16-46b7-8bd8-f6b893a9b7c0}}
    [76]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: e80b3fbc-c417-4577-a83f-5055c2b72e0f} Modified FK {CronTickerId: abc005a9-d164-4834-bf22-c99572148f11}}
    [77]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: eaf52e7c-7e05-47c4-adea-0d473b2d596e} Modified FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}
    [78]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: f28144dd-9589-4b49-bb77-c236cd56c639} Modified FK {CronTickerId: 9adac3c6-144b-4e1f-9ae5-ae381473b851}}
    [79]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: f39db272-a33e-47b5-b726-9999ac6b4599} Modified FK {CronTickerId: d67492b1-89d5-4493-a45e-0873415b7f18}}
    [80]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: f3b438f9-89a2-4f3d-a0f7-821a2c230789} Modified FK {CronTickerId: abc005a9-d164-4834-bf22-c99572148f11}}
    [81]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: f4924feb-4ae0-4e3b-b293-959629076cf8} Modified FK {CronTickerId: abc005a9-d164-4834-bf22-c99572148f11}}
    [82]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: f65e6c31-4bde-4de2-abda-c2be8a32f248} Modified FK {CronTickerId: c424084b-b8dd-415e-857a-53d1514108d8}}
    [83]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: f9bfdf6b-f080-42db-a769-0a06dcf7d448} Modified FK {CronTickerId: c1f38cce-127d-417c-b826-8397f0e93a40}}
    [84]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: fac45564-b061-4f7a-8bd0-bc470d5c9641} Modified FK {CronTickerId: c424084b-b8dd-415e-857a-53d1514108d8}}
    [85]: {CronTickerEntity {Id: 2095b184-199a-4509-a0ed-ac7f3d237c91} Unchanged}
    [86]: {CronTickerEntity {Id: 77831b68-0ec4-476e-be78-57d03745149d} Unchanged}
    [87]: {CronTickerEntity {Id: 9ec1c244-07c9-468b-b6c5-84bc931f40de} Unchanged}
    [88]: {CronTickerEntity {Id: c424084b-b8dd-415e-857a-53d1514108d8} Unchanged}
    [89]: {CronTickerEntity {Id: d67492b1-89d5-4493-a45e-0873415b7f18} Unchanged}
    [90]: {CronTickerEntity {Id: 734f1f78-d4bd-4196-af3e-f92f5190ee0d} Unchanged}
    [91]: {CronTickerEntity {Id: abc005a9-d164-4834-bf22-c99572148f11} Unchanged}
    [92]: {CronTickerEntity {Id: 9adac3c6-144b-4e1f-9ae5-ae381473b851} Unchanged}
    [93]: {CronTickerEntity {Id: c1f38cce-127d-417c-b826-8397f0e93a40} Unchanged}
    [94]: {CronTickerEntity {Id: b8ced09b-ad1b-47ec-9e65-4e228d2804bd} Unchanged}
    [95]: {CronTickerEntity {Id: b87b520f-ed86-47c5-8c26-bde223365cf9} Unchanged}
    [96]: {CronTickerEntity {Id: 9eb787da-09e4-4cb7-a780-15340d21fdf2} Unchanged}
    [97]: {CronTickerEntity {Id: d85df830-4d16-46b7-8bd8-f6b893a9b7c0} Unchanged}

  base.ChangeTracker.Entries().ToList()
  {Count = 2}
    [0]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 25fa80d6-fc37-45a0-942d-18c60cb12e95} Added FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}
    [1]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: e5d54f61-58a2-484c-a59d-010ec400ee47} Unchanged FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}

  base.ChangeTracker.Entries().ToList()
  {Count = 2}
    [0]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 97be91d3-8873-4641-b4b2-255ae1b7cff1} Added FK {CronTickerId: b87b520f-ed86-47c5-8c26-bde223365cf9}}
    [1]: {CronTickerEntity {Id: b87b520f-ed86-47c5-8c26-bde223365cf9} Added}

  base.ChangeTracker.Entries().ToList()
  {Count = 3}
    [0]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: c9e93603-75af-4fdc-9fbe-8947f6838c09} Added FK {CronTickerId: 77831b68-0ec4-476e-be78-57d03745149d}}
    [1]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: e5d54f61-58a2-484c-a59d-010ec400ee47} Unchanged FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}
    [2]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 25fa80d6-fc37-45a0-942d-18c60cb12e95} Unchanged FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}

  base.ChangeTracker.Entries().ToList()
  {Count = 4}
    [0]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: d3264b2b-a04a-49de-90f6-fc7b8f437c51} Added FK {CronTickerId: 9adac3c6-144b-4e1f-9ae5-ae381473b851}}
    [1]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: e5d54f61-58a2-484c-a59d-010ec400ee47} Unchanged FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}
    [2]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 25fa80d6-fc37-45a0-942d-18c60cb12e95} Unchanged FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}
    [3]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: c9e93603-75af-4fdc-9fbe-8947f6838c09} Unchanged FK {CronTickerId: 77831b68-0ec4-476e-be78-57d03745149d}}

  base.ChangeTracker.Entries().ToList()
  {Count = 5}
    [0]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: d138b7c3-5b69-4e56-b3b3-8a1b6df8bdff} Added FK {CronTickerId: abc005a9-d164-4834-bf22-c99572148f11}}
    [1]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: e5d54f61-58a2-484c-a59d-010ec400ee47} Unchanged FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}
    [2]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 25fa80d6-fc37-45a0-942d-18c60cb12e95} Unchanged FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}
    [3]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: c9e93603-75af-4fdc-9fbe-8947f6838c09} Unchanged FK {CronTickerId: 77831b68-0ec4-476e-be78-57d03745149d}}
    [4]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: d3264b2b-a04a-49de-90f6-fc7b8f437c51} Unchanged FK {CronTickerId: 9adac3c6-144b-4e1f-9ae5-ae381473b851}}

  base.ChangeTracker.Entries().ToList()
  {Count = 6}
    [0]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: bb08fd89-7664-4c66-bc5a-a759c31cb85a} Added FK {CronTickerId: c1f38cce-127d-417c-b826-8397f0e93a40}}
    [1]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: e5d54f61-58a2-484c-a59d-010ec400ee47} Unchanged FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}
    [2]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 25fa80d6-fc37-45a0-942d-18c60cb12e95} Unchanged FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}
    [3]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: c9e93603-75af-4fdc-9fbe-8947f6838c09} Unchanged FK {CronTickerId: 77831b68-0ec4-476e-be78-57d03745149d}}
    [4]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: d3264b2b-a04a-49de-90f6-fc7b8f437c51} Unchanged FK {CronTickerId: 9adac3c6-144b-4e1f-9ae5-ae381473b851}}
    [5]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: d138b7c3-5b69-4e56-b3b3-8a1b6df8bdff} Unchanged FK {CronTickerId: abc005a9-d164-4834-bf22-c99572148f11}}

  base.ChangeTracker.Entries().ToList()
  {Count = 7}
    [0]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 7adaf0a0-f6f0-41b1-b67c-99d5735d095d} Added FK {CronTickerId: c424084b-b8dd-415e-857a-53d1514108d8}}
    [1]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: e5d54f61-58a2-484c-a59d-010ec400ee47} Unchanged FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}
    [2]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 25fa80d6-fc37-45a0-942d-18c60cb12e95} Unchanged FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}
    [3]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: c9e93603-75af-4fdc-9fbe-8947f6838c09} Unchanged FK {CronTickerId: 77831b68-0ec4-476e-be78-57d03745149d}}
    [4]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: d3264b2b-a04a-49de-90f6-fc7b8f437c51} Unchanged FK {CronTickerId: 9adac3c6-144b-4e1f-9ae5-ae381473b851}}
    [5]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: d138b7c3-5b69-4e56-b3b3-8a1b6df8bdff} Unchanged FK {CronTickerId: abc005a9-d164-4834-bf22-c99572148f11}}
    [6]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: bb08fd89-7664-4c66-bc5a-a759c31cb85a} Unchanged FK {CronTickerId: c1f38cce-127d-417c-b826-8397f0e93a40}}

  base.ChangeTracker.Entries().ToList()
  {Count = 8}
    [0]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 11a10bee-f167-4a14-a604-8a34ff55ea91} Added FK {CronTickerId: d67492b1-89d5-4493-a45e-0873415b7f18}}
    [1]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: e5d54f61-58a2-484c-a59d-010ec400ee47} Unchanged FK {CronTickerId: 2095b184-199a-4509-a0ed-ac7f3d237c91}}
    [2]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 25fa80d6-fc37-45a0-942d-18c60cb12e95} Unchanged FK {CronTickerId: 734f1f78-d4bd-4196-af3e-f92f5190ee0d}}
    [3]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: c9e93603-75af-4fdc-9fbe-8947f6838c09} Unchanged FK {CronTickerId: 77831b68-0ec4-476e-be78-57d03745149d}}
    [4]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: d3264b2b-a04a-49de-90f6-fc7b8f437c51} Unchanged FK {CronTickerId: 9adac3c6-144b-4e1f-9ae5-ae381473b851}}
    [5]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: d138b7c3-5b69-4e56-b3b3-8a1b6df8bdff} Unchanged FK {CronTickerId: abc005a9-d164-4834-bf22-c99572148f11}}
    [6]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: bb08fd89-7664-4c66-bc5a-a759c31cb85a} Unchanged FK {CronTickerId: c1f38cce-127d-417c-b826-8397f0e93a40}}
    [7]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 7adaf0a0-f6f0-41b1-b67c-99d5735d095d} Unchanged FK {CronTickerId: c424084b-b8dd-415e-857a-53d1514108d8}}

```

</details>

#### Step 8

Caught an exception:

` An exception occurred in the database while saving changes for context type '***.MySql.DbContex.SloDbContext'.`
```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes.
 ---> MySqlConnector.MySqlException (0x80004005): Duplicate entry 'b87b520f-ed86-47c5-8c26-bde223365cf9' for key 'CronTickers.PRIMARY'
```

Full stack trace (click to expand):

<details>
<summary>Stacktrace</summary>

```
 Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> MySqlConnector.MySqlException (0x80004005): Duplicate entry 'b87b520f-ed86-47c5-8c26-bde223365cf9' for key 'CronTickers.PRIMARY'
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 894
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 37
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
   at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 483
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 357      
   at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 350
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)      
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> MySqlConnector.MySqlException (0x80004005): Duplicate entry 'b87b520f-ed86-47c5-8c26-bde223365cf9' for key 'CronTickers.PRIMARY'
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 894
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 37
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
   at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 483
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 357 
```

</details>

#### Step 9

As I suggest, the problem is here:

```
ChangeTracker.Entries().ToList()
{Count = 2}
  [0]: {CronTickerOccurrenceEntity<CronTickerEntity> {Id: 97be91d3-8873-4641-b4b2-255ae1b7cff1} Added FK {CronTickerId: b87b520f-ed86-47c5-8c26-bde223365cf9}}
  [1]: {CronTickerEntity {Id: b87b520f-ed86-47c5-8c26-bde223365cf9} Added}
```

---
